# KenyaComply Web App
# Flask app for Kenyan Business Compliance
# Deployable to Vercel

from flask import Flask, render_template_string, request, jsonify, session, redirect, url_for
import json
import os
import uuid
from datetime import datetime

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'kenyacomply-dev-secret-key')

# Import our modules
from etims_invoice import create_standard_invoice
from tax_calculator import calculate_paye, calculate_vat

# In-memory user store (replace with Supabase in production)
USERS = {}

# ============================================
# AUTH ROUTES
# ============================================

@app.route('/login', methods=['GET', 'POST'])
def login():
    """Login page"""
    if request.method == 'POST':
        email = request.form.get('email', '')
        name = request.form.get('name', '')
        if email:
            if email not in USERS:
                USERS[email] = {'id': str(uuid.uuid4()), 'email': email, 'name': name, 'invoices': []}
            session['user_id'] = USERS[email]['id']
            session['email'] = email
            return redirect(url_for('dashboard'))
    return render_template_string(LOGIN_HTML)

@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

@app.route('/dashboard')
def dashboard():
    """User dashboard"""
    if 'user_id' not in session:
        return redirect(url_for('login'))
    
    user = next((u for u in USERS.values() if u['id'] == session['user_id']), None)
    invoices = user['invoices'] if user else []
    
    return render_template_string(DASHBOARD_HTML, user=user, invoices=invoices)

# Print-friendly invoice page
PRINT_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice - KenyaComply</title>
    <style>
        body { font-family: 'Courier New', monospace; margin: 40px; max-width: 800px; }
        .invoice { border: 2px solid #000; padding: 30px; }
        h1 { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .row { display: flex; justify-content: space-between; margin: 10px 0; }
        .section { margin: 20px 0; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #000; padding: 10px; text-align: left; }
        th { background: #f0f0f0; }
        .total { font-size: 1.3em; font-weight: bold; }
        .print-btn { background: #1a1a2e; color: white; padding: 15px 30px; border: none; cursor: pointer; font-size: 1rem; }
        @media print { .print-btn { display: none; } }
    </style>
</head>
<body>
    <button class="print-btn" onclick="window.print()">🖨️ Print Invoice</button>
    <div class="invoice">
        <h1>🏢 KENYACOMPLY - ETIMS INVOICE</h1>
        
        <div class="section">
            <div class="row"><strong>Invoice Number:</strong> <span>{{invoice_number}}</span></div>
            <div class="row"><strong>Date:</strong> <span>{{date}}</span></div>
        </div>
        
        <div class="section">
            <h3>SELLER</h3>
            <div>{{seller_name}}</div>
            <div>KRA PIN: {{seller_pin}}</div>
        </div>
        
        <div class="section">
            <h3>BUYER</h3>
            <div>{{buyer_name}}</div>
            <div>KRA PIN: {{buyer_pin}}</div>
        </div>
        
        <table>
            <tr>
                <th>Description</th>
                <th>Qty</th>
                <th>Unit Price</th>
                <th>VAT</th>
                <th>Total</th>
            </tr>
            <tr>
                <td>Service</td>
                <td>1</td>
                <td>KES {{subtotal}}</td>
                <td>16%</td>
                <td>KES {{total}}</td>
            </tr>
        </table>
        
        <div class="section total">
            <div class="row"><span>Subtotal:</span> <span>KES {{subtotal}}</span></div>
            <div class="row"><span>VAT (16%):</span> <span>KES {{vat}}</span></div>
            <div class="row"><span>GRAND TOTAL:</span> <span>KES {{total}}</span></div>
        </div>
        
        <p style="text-align: center; margin-top: 30px;">
            Generated by KenyaComply | kenya-comply.vercel.app
        </p>
    </div>
</body>
</html>
"""

# ============================================
# HTML TEMPLATES
# ============================================

LOGIN_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - KenyaComply</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
        .card { background: white; padding: 40px; border-radius: 16px; box-shadow: 0 8px 32px rgba(0,0,0,0.2); width: 100%; max-width: 400px; }
        h1 { color: #1a1a2e; margin-bottom: 10px; text-align: center; }
        .subtitle { color: #666; text-align: center; margin-bottom: 30px; }
        .form-group { margin-bottom: 20px; }
        label { display: block; margin-bottom: 8px; font-weight: 600; color: #333; }
        input { width: 100%; padding: 14px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 1rem; }
        input:focus { outline: none; border-color: #1a1a2e; }
        button { background: #1a1a2e; color: white; padding: 16px; border: none; border-radius: 8px; font-size: 1rem; width: 100%; cursor: pointer; font-weight: 600; }
        button:hover { background: #16213e; }
        .back { display: block; text-align: center; margin-top: 20px; color: #666; text-decoration: none; }
    </style>
</head>
<body>
    <div class="card">
        <h1>🏢 KenyaComply</h1>
        <p class="subtitle">Sign in to manage your business</p>
        <form method="POST">
            <div class="form-group">
                <label>Email</label>
                <input type="email" name="email" required placeholder="you@company.co.ke">
            </div>
            <div class="form-group">
                <label>Your Name</label>
                <input type="text" name="name" required placeholder="John Doe">
            </div>
            <button type="submit">Continue</button>
        </form>
        <a href="/" class="back">← Back to home</a>
    </div>
</body>
</html>
"""

DASHBOARD_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - KenyaComply</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; margin: 0; }
        header { background: #1a1a2e; color: white; padding: 20px; display: flex; justify-content: space-between; align-items: center; }
        .logo { font-size: 1.5rem; font-weight: bold; }
        .container { max-width: 900px; margin: 30px auto; padding: 0 20px; }
        .card { background: white; padding: 25px; border-radius: 12px; margin-bottom: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h2 { color: #1a1a2e; margin: 0 0 20px 0; }
        .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }
        .stat { background: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 2rem; font-weight: bold; color: #1a1a2e; }
        .stat-label { color: #666; font-size: 0.9rem; }
        .invoice { background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 10px; border-left: 4px solid #1a1a2e; }
        .invoice-header { display: flex; justify-content: space-between; margin-bottom: 8px; }
        .invoice-number { font-weight: bold; color: #1a1a2e; }
        .invoice-amount { font-size: 1.2rem; font-weight: bold; color: #2e7d32; }
        .invoice-date { color: #666; font-size: 0.9rem; }
        .btn { display: inline-block; background: #1a1a2e; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600; border: none; cursor: pointer; }
        .btn:hover { background: #16213e; }
        .btn-outline { background: transparent; border: 2px solid #1a1a2e; color: #1a1a2e; }
    </style>
</head>
<body>
    <header>
        <div class="logo">🏢 KenyaComply</div>
        <a href="/logout" style="color: white; text-decoration: none;">Logout</a>
    </header>
    <div class="container">
        <div class="card">
            <h2>Welcome back, {{ user.name }} 👋</h2>
            <p style="color: #666;">Manage your business compliance from one place.</p>
            <a href="/" class="btn">+ Create New Invoice</a>
        </div>
        
        <div class="card">
            <h2>Your Stats</h2>
            <div class="stat-grid">
                <div class="stat">
                    <div class="stat-value">{{ invoices|length }}</div>
                    <div class="stat-label">Invoices Created</div>
                </div>
                <div class="stat">
                    <div class="stat-value">KES {{ "{:,.0f}".format(invoices|sum(attribute='amount')) if invoices else 0 }}</div>
                    <div class="stat-label">Total Billed</div>
                </div>
            </div>
        </div>
        
        <div class="card">
            <h2>Recent Invoices</h2>
            {% if invoices %}
                {% for inv in invoices|reverse %}
                    <div class="invoice">
                        <div class="invoice-header">
                            <span class="invoice-number">{{ inv.number }}</span>
                            <span class="invoice-amount">KES {{ "{:,.0f}".format(inv.amount) }}</span>
                        </div>
                        <div class="invoice-date">{{ inv.buyer }} • {{ inv.date }}</div>
                    </div>
                {% endfor %}
            {% else %}
                <p style="color: #666;">No invoices yet. Create your first one!</p>
            {% endif %}
        </div>
        
        <div class="card">
            <h2>Quick Actions</h2>
            <div style="display: flex; gap: 10px; flex-wrap: wrap;">
                <a href="/" class="btn">📄 New Invoice</a>
                <a href="/" class="btn btn-outline">💰 PAYE Calculator</a>
                <a href="/" class="btn btn-outline">🧾 VAT Calculator</a>
            </div>
        </div>
    </div>
</body>
</html>
"""

# Main HTML Template
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KenyaComply - Business Compliance Simplified</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; line-height: 1.6; }
        .container { max-width: 800px; margin: 0 auto; padding: 20px; }
        header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: white; padding: 40px 20px; text-align: center; border-radius: 10px; margin-bottom: 30px; }
        h1 { font-size: 2.5rem; margin-bottom: 10px; }
        .subtitle { opacity: 0.8; font-size: 1.1rem; }
        .nav { display: flex; justify-content: center; gap: 15px; margin-bottom: 20px; flex-wrap: wrap; }
        .nav-link { color: white; text-decoration: none; padding: 8px 16px; border-radius: 20px; background: rgba(255,255,255,0.1); }
        .nav-link:hover { background: rgba(255,255,255,0.2); }
        .tabs { display: flex; gap: 10px; margin-bottom: 20px; flex-wrap: wrap; }
        .tab { padding: 12px 24px; background: white; border: none; border-radius: 8px; cursor: pointer; font-size: 1rem; transition: all 0.3s; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        .tab:hover { transform: translateY(-2px); }
        .tab.active { background: #1a1a2e; color: white; }
        .card { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); margin-bottom: 20px; }
        .form-group { margin-bottom: 20px; }
        label { display: block; margin-bottom: 8px; font-weight: 600; }
        input, select, textarea { width: 100%; padding: 12px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 1rem; transition: border-color 0.3s; }
        input:focus, select:focus, textarea:focus { outline: none; border-color: #1a1a2e; }
        .row { display: flex; gap: 15px; flex-wrap: wrap; }
        .col { flex: 1; min-width: 200px; }
        button.primary { background: #1a1a2e; color: white; padding: 15px 30px; border: none; border-radius: 8px; font-size: 1.1rem; cursor: pointer; width: 100%; transition: all 0.3s; }
        button.primary:hover { background: #16213e; transform: translateY(-2px); }
        .result { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-top: 20px; border-left: 4px solid #1a1a2e; }
        .result h3 { margin-bottom: 15px; color: #1a1a2e; }
        .result-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #e0e0e0; }
        .result-row:last-child { border-bottom: none; font-weight: bold; font-size: 1.2rem; }
        .download-btn, .print-btn { background: #2e7d32; color: white; padding: 14px 24px; border: none; border-radius: 8px; font-size: 1rem; cursor: pointer; margin-top: 15px; font-weight: 600; }
        .print-btn { background: #1565c0; margin-left: 10px; }
        .download-btn:hover { background: #1b5e20; }
        .print-btn:hover { background: #0d47a1; }
        .btn-row { display: flex; gap: 10px; margin-top: 15px; }
        .payment-notice { background: #fff3cd; color: #856404; padding: 15px; border-radius: 8px; margin-bottom: 15px; font-weight: 600; text-align: center; }
        .payment-status { background: #d4edda; color: #155724; padding: 10px; border-radius: 8px; margin: 15px 0; text-align: center; font-weight: 600; }
        .badge { display: inline-block; background: #e8f5e9; color: #2e7d32; padding: 5px 12px; border-radius: 20px; font-size: 0.85rem; margin-right: 5px; }
        footer { text-align: center; padding: 20px; opacity: 0.7; font-size: 0.9rem; }
        .hidden { display: none; }
        @media (max-width: 600px) { .container { padding: 10px; } .card { padding: 20px; } h1 { font-size: 1.8rem; } }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🏢 KenyaComply</h1>
            <p class="subtitle">Kenyan Business Compliance, Simplified</p>
            <div style="margin-top: 15px;">
                <span class="badge">ETIMS Invoices</span>
                <span class="badge">Tax Calculator</span>
                <span class="badge">KRA Compliant</span>
            </div>
            <div class="nav" style="margin-top: 20px;">
                <a href="/login" class="nav-link">Login</a>
                <a href="/dashboard" class="nav-link">Dashboard</a>
            </div>
        </header>
        
        <div class="tabs">
            <button class="tab active" onclick="showTab('invoice')">📄 Generate Invoice</button>
            <button class="tab" onclick="showTab('paye')">💰 PAYE Calculator</button>
            <button class="tab" onclick="showTab('vat')">🧾 VAT Calculator</button>
        </div>
        
        <!-- Invoice Form -->
        <div id="invoice" class="card">
            <h2>Generate ETIMS Invoice</h2>
            <form id="invoiceForm">
                <div class="row">
                    <div class="col form-group">
                        <label>Seller Name</label>
                        <input type="text" name="seller_name" placeholder="Your Company Ltd" required>
                    </div>
                    <div class="col form-group">
                        <label>Seller KRA PIN</label>
                        <input type="text" name="seller_pin" placeholder="P051234567A" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label>Buyer Name</label>
                        <input type="text" name="buyer_name" placeholder="Client Company Ltd" required>
                    </div>
                    <div class="col form-group">
                        <label>Buyer KRA PIN</label>
                        <input type="text" name="buyer_pin" placeholder="P098765432B" required>
                    </div>
                </div>
                <div class="form-group">
                    <label>Amount (KES)</label>
                    <input type="number" name="amount" placeholder="50000" required>
                </div>
                <button type="submit" class="primary">💰 Pay KES 50 & Generate</button>
            </form>
            <div id="invoiceResult" class="result hidden"></div>
        </div>
        
        <!-- PAYE Form -->
        <div id="paye" class="card hidden">
            <h2>Calculate PAYE Tax</h2>
            <form id="payeForm">
                <div class="form-group">
                    <label>Gross Monthly Salary (KES)</label>
                    <input type="number" name="salary" placeholder="250000" required>
                </div>
                <button type="submit" class="primary">Calculate PAYE</button>
            </form>
            <div id="payeResult" class="result hidden"></div>
        </div>
        
        <!-- VAT Form -->
        <div id="vat" class="card hidden">
            <h2>Calculate VAT</h2>
            <form id="vatForm">
                <div class="form-group">
                    <label>Output Sales (KES)</label>
                    <input type="number" name="sales" placeholder="100000" required>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label>Exempt Sales (KES)</label>
                        <input type="number" name="exempt" placeholder="0">
                    </div>
                    <div class="col form-group">
                        <label>Input VAT (KES)</label>
                        <input type="number" name="input_vat" placeholder="0">
                    </div>
                </div>
                <button type="submit" class="primary">Calculate VAT</button>
            </form>
            <div id="vatResult" class="result hidden"></div>
        </div>
        
        <footer>
            <p>Built by Mwakulomba 🎥📜 | KenyaComply v1.1</p>
        </footer>
    </div>
    
    <script>
        function showTab(tabId) {
            document.querySelectorAll('.card').forEach(c => c.classList.add('hidden'));
            document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
            document.getElementById(tabId).classList.remove('hidden');
            event.target.classList.add('active');
        }
        
        function downloadInvoice(filename, text) {
            const blob = new Blob([text], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename + '.txt';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }
        
        document.getElementById('invoiceForm').addEventListener('submit', async (e) => {
            e.preventDefault();
            const formData = new FormData(e.target);
            const data = Object.fromEntries(formData);
            data.amount = parseFloat(data.amount);
            
            // Show payment required notice
            const confirmPay = confirm("Generate invoice for KES 50? (Demo mode - no actual payment)");
            
            if (!confirmPay) return;
            
            // Add demo fee
            document.getElementById('invoiceResult').innerHTML = `
                <div class="payment-notice">💳 Payment: KES 50 (Demo Mode)</div>
            `;
            document.getElementById('invoiceResult').classList.remove('hidden');
            
            const response = await fetch('/api/invoice', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(data)
            });
            const result = await response.json();
            
            document.getElementById('invoiceResult').innerHTML = `
                <h3>✅ Invoice Generated (KES 50 Paid)</h3>
                <div class="result-row"><span>Invoice Number</span><span>${result.invoice_number}</span></div>
                <div class="result-row"><span>Date</span><span>${result.date}</span></div>
                <div class="result-row"><span>Subtotal</span><span>KES ${result.subtotal.toLocaleString()}</span></div>
                <div class="result-row"><span>VAT (16%)</span><span>KES ${result.vat.toLocaleString()}</span></div>
                <div class="result-row"><span>Grand Total</span><span>KES ${result.total.toLocaleString()}</span></div>
                <div class="payment-status">✓ KES 50 payment confirmed</div>
                <div class="btn-row">
                <button class="download-btn" onclick="downloadInvoice('${result.invoice_number}', '${result.download_text.replace(/'/g, "\\'")}')">📥 Download</button>
                <button class="print-btn" onclick="window.print()">🖨️ Print / PDF</button>
                </div>
            `;
        });
        
        document.getElementById('payeForm').addEventListener('submit', async (e) => {
            e.preventDefault();
            const formData = new FormData(e.target);
            const data = {salary: parseFloat(formData.get('salary'))};
            
            const response = await fetch('/api/paye', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(data)
            });
            const result = await response.json();
            
            document.getElementById('payeResult').innerHTML = `
                <h3>✅ PAYE Calculated</h3>
                <div class="result-row"><span>Gross Salary</span><span>KES ${result.gross_salary.toLocaleString()}</span></div>
                <div class="result-row"><span>NSSF</span><span>KES ${result.nssf.toLocaleString()}</span></div>
                <div class="result-row"><span>Taxable Income</span><span>KES ${result.taxable_income.toLocaleString()}</span></div>
                <div class="result-row"><span>Tax (after relief)</span><span>KES ${result.tax_after_relief.toLocaleString()}</span></div>
                <div class="result-row"><span>NHIF</span><span>KES ${result.nhif.toLocaleString()}</span></div>
                <div class="result-row"><span>NET SALARY</span><span>KES ${result.net_salary.toLocaleString()}</span></div>
            `;
            document.getElementById('payeResult').classList.remove('hidden');
        });
        
        document.getElementById('vatForm').addEventListener('submit', async (e) => {
            e.preventDefault();
            const formData = new FormData(e.target);
            const data = {
                sales: parseFloat(formData.get('sales')),
                exempt: parseFloat(formData.get('exempt') || 0),
                input_vat: parseFloat(formData.get('input_vat') || 0)
            };
            
            const response = await fetch('/api/vat', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(data)
            });
            const result = await response.json();
            
            document.getElementById('vatResult').innerHTML = `
                <h3>✅ VAT Calculated</h3>
                <div class="result-row"><span>Output Sales</span><span>KES ${result.gross_sales.toLocaleString()}</span></div>
                <div class="result-row"><span>Exempt Sales</span><span>KES ${result.vat_exempt.toLocaleString()}</span></div>
                <div class="result-row"><span>VAT Collected</span><span>KES ${result.vat_collected.toLocaleString()}</span></div>
                <div class="result-row"><span>Input VAT</span><span>KES ${result.input_vat.toLocaleString()}</span></div>
                <div class="result-row"><span>NET VAT PAYABLE</span><span>KES ${result.net_vat_payable.toLocaleString()}</span></div>
            `;
            document.getElementById('vatResult').classList.remove('hidden');
        });
    </script>
</body>
</html>
"""

# ============================================
# API ROUTES
# ============================================

@app.route("/")
def index():
    return render_template_string(HTML_TEMPLATE)

@app.route("/api/invoice", methods=["POST"])
def api_invoice():
    data = request.json
    invoice = create_standard_invoice(
        seller_name=data["seller_name"],
        seller_pin=data["seller_pin"],
        seller_address="Nairobi, Kenya",
        seller_phone="+254700000000",
        buyer_name=data["buyer_name"],
        buyer_pin=data["buyer_pin"],
        buyer_address="Kenya",
        items=[{"description": "Service", "quantity": 1, "unit_price": data["amount"], "vat_rate": 16}]
    )
    
    # Generate downloadable content
    invoice_text = f"""
KENYACOMPLY ETIMS INVOICE
========================
Invoice Number: {invoice.invoice_number}
Date: {invoice.date}

SELLER:
{data['seller_name']}
KRA PIN: {data['seller_pin']}
Address: Nairobi, Kenya

BUYER:
{data['buyer_name']}
KRA PIN: {data['buyer_pin']}

ITEMS:
Description     | Qty | Unit Price | VAT Rate | Total
Service         |  1  | {data['amount']:,.2f}  |   16%   | {data['amount']:,.2f}

Subtotal: {invoice.subtotal:,.2f}
VAT (16%): {invoice.total_vat:,.2f}
------------------------
GRAND TOTAL: KES {invoice.grand_total:,.2f}

Generated by KenyaComply - kenya-comply.vercel.app
"""
    
    # Save to user if logged in
    if 'user_id' in session:
        user = next((u for u in USERS.values() if u['id'] == session['user_id']), None)
        if user:
            user['invoices'].append({
                'number': invoice.invoice_number,
                'amount': invoice.grand_total,
                'buyer': data["buyer_name"],
                'date': invoice.date,
                'seller': data["seller_name"]
            })
    
    return jsonify({
        "invoice_number": invoice.invoice_number,
        "date": invoice.date,
        "subtotal": invoice.subtotal,
        "vat": invoice.total_vat,
        "total": invoice.grand_total,
        "download_text": invoice_text
    })

@app.route("/api/paye", methods=["POST"])
def api_paye():
    data = request.json
    result = calculate_paye(data["salary"])
    return jsonify(result.to_dict())

@app.route("/api/vat", methods=["POST"])
def api_vat():
    data = request.json
    result = calculate_vat(data["sales"], data.get("exempt", 0), data.get("input_vat", 0))
    return jsonify({
        "gross_sales": result.gross_sales,
        "vat_exempt": result.vat_exempt,
        "vat_collected": result.vat_collected,
        "input_vat": result.input_vat,
        "net_vat_payable": result.net_vat_payable
    })

@app.route("/print/<invoice_number>")
def print_invoice(invoice_number):
    """Print-friendly invoice view"""
    # Find invoice in any user's data
    invoice_data = None
    for user in USERS.values():
        for inv in user.get('invoices', []):
            if inv['number'] == invoice_number:
                invoice_data = inv
                break
    
    if not invoice_data:
        return "Invoice not found", 404
    
    return render_template_string(PRINT_HTML,
        invoice_number=invoice_data['number'],
        date=invoice_data['date'],
        seller_name=invoice_data.get('seller', 'N/A'),
        seller_pin='P000000000',
        buyer_name=invoice_data['buyer'],
        buyer_pin='P000000000',
        subtotal=invoice_data['amount'] / 1.16,
        vat=invoice_data['amount'] * 0.16 / 1.16,
        total=invoice_data['amount']
    )

@app.route("/health")
def health():
    return {"status": "ok", "service": "kenya-comply"}

# Run the app
app.debug = True
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)